# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/maximyarosh/lab6/llp-lab-6-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/maximyarosh/lab6/llp-lab-6-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maximyarosh/lab6/llp-lab-6-master/CMakeFiles /home/maximyarosh/lab6/llp-lab-6-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maximyarosh/lab6/llp-lab-6-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named llp_lab_6_

# Build rule for target.
llp_lab_6_: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 llp_lab_6_
.PHONY : llp_lab_6_

# fast build rule for target.
llp_lab_6_/fast:
	$(MAKE) -f CMakeFiles/llp_lab_6_.dir/build.make CMakeFiles/llp_lab_6_.dir/build
.PHONY : llp_lab_6_/fast

# target to build an object file
src/lib/bmp_io.o:
	$(MAKE) -f CMakeFiles/llp_lab_6_.dir/build.make CMakeFiles/llp_lab_6_.dir/src/lib/bmp_io.o
.PHONY : src/lib/bmp_io.o

# target to preprocess a source file
src/lib/bmp_io.i:
	$(MAKE) -f CMakeFiles/llp_lab_6_.dir/build.make CMakeFiles/llp_lab_6_.dir/src/lib/bmp_io.i
.PHONY : src/lib/bmp_io.i

# target to generate assembly for a file
src/lib/bmp_io.s:
	$(MAKE) -f CMakeFiles/llp_lab_6_.dir/build.make CMakeFiles/llp_lab_6_.dir/src/lib/bmp_io.s
.PHONY : src/lib/bmp_io.s

# target to build an object file
src/lib/bmp_transform.o:
	$(MAKE) -f CMakeFiles/llp_lab_6_.dir/build.make CMakeFiles/llp_lab_6_.dir/src/lib/bmp_transform.o
.PHONY : src/lib/bmp_transform.o

# target to preprocess a source file
src/lib/bmp_transform.i:
	$(MAKE) -f CMakeFiles/llp_lab_6_.dir/build.make CMakeFiles/llp_lab_6_.dir/src/lib/bmp_transform.i
.PHONY : src/lib/bmp_transform.i

# target to generate assembly for a file
src/lib/bmp_transform.s:
	$(MAKE) -f CMakeFiles/llp_lab_6_.dir/build.make CMakeFiles/llp_lab_6_.dir/src/lib/bmp_transform.s
.PHONY : src/lib/bmp_transform.s

# target to build an object file
src/main.o:
	$(MAKE) -f CMakeFiles/llp_lab_6_.dir/build.make CMakeFiles/llp_lab_6_.dir/src/main.o
.PHONY : src/main.o

# target to preprocess a source file
src/main.i:
	$(MAKE) -f CMakeFiles/llp_lab_6_.dir/build.make CMakeFiles/llp_lab_6_.dir/src/main.i
.PHONY : src/main.i

# target to generate assembly for a file
src/main.s:
	$(MAKE) -f CMakeFiles/llp_lab_6_.dir/build.make CMakeFiles/llp_lab_6_.dir/src/main.s
.PHONY : src/main.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... llp_lab_6_"
	@echo "... edit_cache"
	@echo "... src/lib/bmp_io.o"
	@echo "... src/lib/bmp_io.i"
	@echo "... src/lib/bmp_io.s"
	@echo "... src/lib/bmp_transform.o"
	@echo "... src/lib/bmp_transform.i"
	@echo "... src/lib/bmp_transform.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

